### PR TITLE
(test) Travis tests with cache as well

### PR DESCRIPTION
**Pull request by Hoverbear**
Still builds/tests with the normal features as well to avoid missing anything.

### CODE REVIEW

**Comment by Hoverbear** [comment]
Ohohoh.

**Comment by gsquire** [comment]
Looks like the API changed in `iron-test` 0.4 in b41b0e5ab68d3af085eb4d200e26e3b23d4b6b70?

**Comment by Hoverbear** [comment]
Yup looks like it!

**Comment by gsquire** [comment]
@Hoverbear Sorry I didn't mean to close this...should be fixed now with my PR merged.

**Comment by Hoverbear** [comment]
You didn't close it, I did! =D

**Comment by gsquire** [comment]
Well I put "fixes 84" :)

**Comment by shepmaster** [comment]
Thanks, both of you!

**Comment by Hoverbear** [comment]
Thank @gsquire , I just got the satisfaction of button pushing.

**Comment by gsquire** [comment]
@Hoverbear I just thought you would want to turn on the cache feature build/tests on in Travis. But if you trust me then that is cool too :)

**Pull request closed without merging**
