### PR TITLE
Set an ETag along Last-Modified.

### PR DESCRIPTION
**Pull request by stephank**
Quick stab at this, curious to hear what you think! (Good idea, bad idea?) This particular behavior roughly matches Node.js / Express, generating for example: `W/d-588658dd.0`

### CODE REVIEW

**Comment by stephank** [comment]
Unrelated CI failure, but I fixed it anyway! :)

**Comment by stephank** [comment]
That's actually a very good question, which I hadn't even thought of. I went off implementing this for completeness, more than a real practical reason.

From what I gather, `ETag` can be strong or weak, and  `Last-Modified` is always weak. Strong would indicate contents are exactly the same, and would probably involve (expensive) hashing for us. Weak just means clients can do cache validation, and the content is only semantically the same. (http://stackoverflow.com/a/1560098/224129)

On top of `Last-Modified`, the `ETag` header value in this PR adds filesize as a factor, which is a small benefit I suppose. Besides that, I'm not sure if there are (proxy) clients out there that'd draw additional benefit from the presence of `ETag` on top of `Last-Modified`.

I rebased on master.

**Comment by Hoverbear** [comment]
Are you happy with with this is for now, or would you like to look into Strong `ETag`s as well?

**Comment by stephank** [comment]
Thanks, I'm happy with this as is! :)

Fwiw, strong ETags seem difficult to implement, and would probably have to be an option because of the performance implications. You'd have to buffer the entire response to hash it on the fly and still send the header, or cache the hash somehow and put some trust in your user.

Seems like something that could use an actual use case to offer some more insight before implementing. I don't have one. :)

**Comment by Hoverbear** [comment]
Great. Okay. :) I'm going to merge this. Thanks!

**Pull request merged**
