### PR TITLE
Return in Cache::handler if there's no IfModifiedSince header

### PR DESCRIPTION
**Pull request by upsuper**
It makes no sense to read file metadata if the client does not send the IfModifiedSince header at all.

### CODE REVIEW

**Comment by upsuper** [comment]
Fails because iron-test cannot be built with stable Rust :(

I've filed reem/iron-test#18 to make that work.

**Comment by upsuper** [comment]
ping?

**Comment by reem** [comment]
Looks good! Thanks for the changes, both here and in iron-test.

**Comment by upsuper** [comment]
Hmmm, it seems this change is totally wrong. How did it compile and pass tests... Sorry for it.

**Comment by reem** [comment]
Urgh, that's unusual.

**Pull request merged**
