### PR TITLE
(fix) Allow building with the cache feature again

### PR DESCRIPTION
**Pull request by shepmaster**

### CODE REVIEW

**Comment by shepmaster** [comment]
I humbly suggest that turning on this feature in Travis might be a good idea.

**Comment by gsquire** [comment]
@shepmaster Good catch, I should have seen that this code was behind a feature flag :(

**Comment by Hoverbear** [comment]
Thanks Jake!

**Comment by Hoverbear** [comment]
```rust
cargo build --features "cache"
cargo test --features "cache"
```

Should be what Travis tests with. PR incoming.

**Comment by Hoverbear** [comment]
@shepmaster Looks like building with cache has red tests on travis (See #84).

**Pull request merged**
