### PR TITLE
bump up to iron 0.6

### PR DESCRIPTION
**Pull request by iori-yja**

### CODE REVIEW

**Comment by untitaker** [comment]
Apparently this broke the build, please fix

**Comment by iori-yja** [comment]
Yes, it is broken now because `iron-test` must be upgraded, that requires urlencoded and body-parser to be upgraded... I set it as WIP for now.

**Comment by kyegupov** [comment]
urlencoded has been bumped, this should work

**Comment by untitaker** [comment]
It is blocked by iron-test

**Comment by robinst** [comment]
iron-test 0.6.0 has been released, maybe the PR would build now if we re-trigger the build.

**Comment by durka** [comment]
This builds locally for me, even without the "range versioning" commit.

**Comment by durka** [comment]
This is the last thread tying my project to iron 0.5, would be really great to lose it.

**Comment by robinst** [comment]
@untitaker can you rerun the build please?

**Comment by untitaker** [comment]
Thx!

**Pull request merged**
